# Generated by Django 4.2.7 on 2023-11-20 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='feat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feats', to='main.musician'),
        ),
        migrations.AlterField(
            model_name='song',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
