# Generated by Django 4.2.7 on 2023-11-20 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_human_bank_alter_human_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='name',
        ),
        migrations.RemoveField(
            model_name='human',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='human',
            name='card',
        ),
        migrations.AddField(
            model_name='card',
            name='card_number',
            field=models.PositiveBigIntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.human'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='type',
            field=models.CharField(choices=[('VISA', 'Visa'), ('ELCARD', 'Elcard'), ('MASTER CARD', 'Master Card')], default='VISA', max_length=100),
        ),
        migrations.AlterField(
            model_name='human',
            name='passport_id',
            field=models.IntegerField(unique=True),
        ),
    ]
