# Generated by Django 4.2.7 on 2023-11-21 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='students',
            field=models.ManyToManyField(null=True, related_name='groups', to='group.student'),
        ),
    ]
